theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.lsp]
display-inlay-hints = true

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-p = "file_picker"
C-f = "global_search"
C-e = "scroll_down"
C-y = "scroll_up"

[keys.insert]
j = { k = "normal_mode", j = "normal_mode" } 
C-s = ["normal_mode", ":w"]
