#
# rust
#

[[language]]
name = "rust"
auto-format = true

#
# typescript
# 
[[language]]
name = "typescript"
auto-format = true
language-servers = [{name = "typescript-language-server", except-features = ["format"]}]
formatter = { command = 'prettier', args = ["--stdin", "--parser", "typescript"] }

[[language]]
name = "tsx"
auto-format = true
language-servers = [{name = "typescript-language-server", except-features = ["format"]}]
formatter = { command = 'prettier', args = ["--stdin", "--parser", "typescript"] }

[language-server.typescript-language-server.config.typescript.inlayHints]
includeInlayEnumMemberValueHints = false
includeInlayFunctionLikeReturnTypeHints = false
includeInlayFunctionParameterTypeHints = false
includeInlayParameterNameHints = false
includeInlayParameterNameHintsWhenArgumentMatchesName = false
includeInlayPropertyDeclarationTypeHints = false
includeInlayVariableTypeHints = true

#
# solidity
#
[[language]]
name = "solidity"
auto-format = true
formatter = { command = "/home/naps62/.foundry/bin/forge", args = ["fmt", "--raw", "-"] }

#
# typst
#

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "typst"
roots = []
comment-token = "//"
file-types = ["typ"]
indent = { tab-width = 2, unit = " " }
language-servers = [ "typst-lsp" ]
text-width = 100
rulers = [100]
soft-wrap.wrap-at-text-width = true
