env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 0
    y: 0

  dynamic_title: true

draw_bold_text_with_bright_colors: true

# Font configuration (changes require restart)
#
# Important font attributes like antialiasing, subpixel aa, and hinting can be
# controlled through fontconfig. Specifically, the following attributes should
# have an effect:
#
# * hintstyle
# * antialias
# * lcdfilter
# * rgba
#
# For instance, if you wish to disable subpixel antialiasing, you might set the
# rgba property to "none". If you wish to completely disable antialiasing, you
# can set antialias to false.
#
# Please see these resources for more information on how to use fontconfig
#
# * https://wiki.archlinux.org/index.php/font_configuration#Fontconfig_configuration
# * file:///usr/share/doc/fontconfig/fontconfig-user.html
font:
  # The normal (roman) font face to use.
  normal:
    family: Fira Code Nerd Font # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Fira Code Nerd Font # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Fira Code Nerd Font # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Italic

  # Point size of the font
  size: 12.0

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Possible values for `animation`
# `Ease`
# `EaseOut`
# `EaseOutSine`
# `EaseOutQuad`
# `EaseOutCubic`
# `EaseOutQuart`
# `EaseOutQuint`
# `EaseOutExpo`
# `EaseOutCirc`
# `Linear`
#
# To completely disable the visual bell, set its duration to 0.
#
bell:
  animation: EaseOutExpo
  duration: 0

# Background opacity
background_opacity: 1.0

# Mouse bindings
#
# Currently doesn't support modifiers. Both the `mouse` and `action` fields must
# be specified.
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# Values for `action`:
# - Paste
# - PasteSelection
# - Copy (TODO)
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  hide_when_typing: true
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # Faux Scrollback
  #
  # The `faux_scrollback_lines` setting controls the number
  # of lines the terminal should scroll when the alternate
  # screen buffer is active. This is used to allow mouse
  # scrolling for applications like `man`.
  #
  # To disable this completely, set `faux_scrollback_lines` to 0.
  faux_scrolling_lines: 1

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

cursor:
  # Style of the cursor
  #
  # Values for 'cursor_style':
  # - Block
  # - Underline
  # - Beam
  style: Block

# Live config reload (changes require restart)
live_config_reload: true

# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#
# shell:
#   program: /bin/bash
#   args:
#     - --login
# Key bindings
#
# Each binding is defined as an object with some properties. Most of the
# properties are optional. All of the alphabetical keys should have a letter for
# the `key` value such as `V`. Function keys are probably what you would expect
# as well (F1, F2, ..). The number keys above the main keyboard are encoded as
# `Key1`, `Key2`, etc. Keys on the number pad are encoded `Number1`, `Number2`,
# etc.  These all match the glutin::VirtualKeyCode variants.
#
# A list with all available `key` names can be found here:
# https://docs.rs/glutin/*/glutin/enum.VirtualKeyCode.html#variants
#
# Possible values for `mods`
# `Command`, `Super` refer to the super/command/windows key
# `Control` for the control key
# `Shift` for the Shift key
# `Alt` and `Option` refer to alt/option
#
# mods may be combined with a `|`. For example, requiring control and shift
# looks like:
#
# mods: Control|Shift
#
# The parser is currently quite sensitive to whitespace and capitalization -
# capitalization must match exactly, and piped items must not have whitespace
# around them.
#
# Either an `action`, `chars`, or `command` field must be present.
#   `action` must be one of `Paste`, `PasteSelection`, `Copy`, or `Quit`.
#   `chars` writes the specified string every time that binding is activated.
#     These should generally be escape sequences, but they can be configured to
#     send arbitrary strings of bytes.
#   `command` must be a map containing a `program` string, and `args` array of
#     strings. For example:
#     - { ... , command: { program: "alacritty", args: ["-e", "vttest"] } }
#
# Want to add a binding (e.g. "PageUp") but are unsure what the X sequence
# (e.g. "\x1b[5~") is? Open another terminal (like xterm) without tmux,
# then run `showkey -a` to get the sequence associated to a key combination.
key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Q, mods: Command, action: Quit }
  - { key: W, mods: Command, action: Quit }
  - { key: Insert, mods: Shift, action: PasteSelection }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - {
      key: Apostrophe,
      mods: Control,
      action: IncreaseFontSize
    }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: Home, chars: "\eOH", mode: AppCursor }
  - { key: Home, chars: "\e[H", mode: ~AppCursor }
  - { key: End, chars: "\eOF", mode: AppCursor }
  - { key: End, chars: "\e[F", mode: ~AppCursor }
  - { key: PageUp, mods: Shift, chars: "\e[5;2~" }
  - { key: PageUp, mods: Control, chars: "\e[5;5~" }
  - { key: PageUp, chars: "\e[5~" }
  - { key: PageDown, mods: Shift, chars: "\e[6;2~" }
  - { key: PageDown, mods: Control, chars: "\e[6;5~" }
  - { key: PageDown, chars: "\e[6~" }
  - { key: Tab, mods: Shift, chars: "\e[Z" }
  - { key: Back, chars: "" }
  - { key: Back, mods: Alt, chars: "\e" }
  - { key: Insert, chars: "\e[2~" }
  - { key: Delete, chars: "\e[3~" }
  - { key: Left, mods: Shift, chars: "\e[1;2D" }
  - { key: Left, mods: Control, chars: "\e[1;5D" }
  - { key: Left, mods: Alt, chars: "\e[1;3D" }
  - { key: Left, chars: "\e[D", mode: ~AppCursor }
  - { key: Left, chars: "\eOD", mode: AppCursor }
  - { key: Right, mods: Shift, chars: "\e[1;2C" }
  - { key: Right, mods: Control, chars: "\e[1;5C" }
  - { key: Right, mods: Alt, chars: "\e[1;3C" }
  - { key: Right, chars: "\e[C", mode: ~AppCursor }
  - { key: Right, chars: "\eOC", mode: AppCursor }
  - { key: Up, mods: Shift, chars: "\e[1;2A" }
  - { key: Up, mods: Control, chars: "\e[1;5A" }
  - { key: Up, mods: Alt, chars: "\e[1;3A" }
  - { key: Up, chars: "\e[A", mode: ~AppCursor }
  - { key: Up, chars: "\eOA", mode: AppCursor }
  - { key: Down, mods: Shift, chars: "\e[1;2B" }
  - { key: Down, mods: Control, chars: "\e[1;5B" }
  - { key: Down, mods: Alt, chars: "\e[1;3B" }
  - { key: Down, chars: "\e[B", mode: ~AppCursor }
  - { key: Down, chars: "\eOB", mode: AppCursor }
  - { key: F1, chars: "\eOP" }
  - { key: F2, chars: "\eOQ" }
  - { key: F3, chars: "\eOR" }
  - { key: F4, chars: "\eOS" }
  - { key: F5, chars: "\e[15~" }
  - { key: F6, chars: "\e[17~" }
  - { key: F7, chars: "\e[18~" }
  - { key: F8, chars: "\e[19~" }
  - { key: F9, chars: "\e[20~" }
  - { key: F10, chars: "\e[21~" }
  - { key: F11, chars: "\e[23~" }
  - { key: F12, chars: "\e[24~" }
  - { key: F1, mods: Shift, chars: "\e[1;2P" }
  - { key: F2, mods: Shift, chars: "\e[1;2Q" }
  - { key: F3, mods: Shift, chars: "\e[1;2R" }
  - { key: F4, mods: Shift, chars: "\e[1;2S" }
  - { key: F5, mods: Shift, chars: "\e[15;2~" }
  - { key: F6, mods: Shift, chars: "\e[17;2~" }
  - { key: F7, mods: Shift, chars: "\e[18;2~" }
  - { key: F8, mods: Shift, chars: "\e[19;2~" }
  - { key: F9, mods: Shift, chars: "\e[20;2~" }
  - { key: F10, mods: Shift, chars: "\e[21;2~" }
  - { key: F11, mods: Shift, chars: "\e[23;2~" }
  - { key: F12, mods: Shift, chars: "\e[24;2~" }
  - { key: F1, mods: Control, chars: "\e[1;5P" }
  - { key: F2, mods: Control, chars: "\e[1;5Q" }
  - { key: F3, mods: Control, chars: "\e[1;5R" }
  - { key: F4, mods: Control, chars: "\e[1;5S" }
  - { key: F5, mods: Control, chars: "\e[15;5~" }
  - { key: F6, mods: Control, chars: "\e[17;5~" }
  - { key: F7, mods: Control, chars: "\e[18;5~" }
  - { key: F8, mods: Control, chars: "\e[19;5~" }
  - { key: F9, mods: Control, chars: "\e[20;5~" }
  - { key: F10, mods: Control, chars: "\e[21;5~" }
  - { key: F11, mods: Control, chars: "\e[23;5~" }
  - { key: F12, mods: Control, chars: "\e[24;5~" }
  - { key: F1, mods: Alt, chars: "\e[1;6P" }
  - { key: F2, mods: Alt, chars: "\e[1;6Q" }
  - { key: F3, mods: Alt, chars: "\e[1;6R" }
  - { key: F4, mods: Alt, chars: "\e[1;6S" }
  - { key: F5, mods: Alt, chars: "\e[15;6~" }
  - { key: F6, mods: Alt, chars: "\e[17;6~" }
  - { key: F7, mods: Alt, chars: "\e[18;6~" }
  - { key: F8, mods: Alt, chars: "\e[19;6~" }
  - { key: F9, mods: Alt, chars: "\e[20;6~" }
  - { key: F10, mods: Alt, chars: "\e[21;6~" }
  - { key: F11, mods: Alt, chars: "\e[23;6~" }
  - { key: F12, mods: Alt, chars: "\e[24;6~" }
  - { key: F1, mods: Super, chars: "\e[1;3P" }
  - { key: F2, mods: Super, chars: "\e[1;3Q" }
  - { key: F3, mods: Super, chars: "\e[1;3R" }
  - { key: F4, mods: Super, chars: "\e[1;3S" }
  - { key: F5, mods: Super, chars: "\e[15;3~" }
  - { key: F6, mods: Super, chars: "\e[17;3~" }
  - { key: F7, mods: Super, chars: "\e[18;3~" }
  - { key: F8, mods: Super, chars: "\e[19;3~" }
  - { key: F9, mods: Super, chars: "\e[20;3~" }
  - { key: F10, mods: Super, chars: "\e[21;3~" }
  - { key: F11, mods: Super, chars: "\e[23;3~" }
  - { key: F12, mods: Super, chars: "\e[24;3~" }

# Base16 Eighties - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  name: Eighties (dark)
  author: Chris Kempson
  primary:
    background: "#2d2d2d"
    foreground: "#d3d0c8"
  cursor:
    text: "#2d2d2d"
    cursor: "#d3d0c8"
  normal:
    black: "#2d2d2d"
    red: "#f2777a"
    green: "#99cc99"
    yellow: "#ffcc66"
    blue: "#6699cc"
    magenta: "#cc99cc"
    cyan: "#66cccc"
    white: "#d3d0c8"
  bright:
    black: "#747369"
    red: "#f2777a"
    green: "#99cc99"
    yellow: "#ffcc66"
    blue: "#6699cc"
    magenta: "#cc99cc"
    cyan: "#66cccc"
    white: "#f2f0ec"
  indexed_colors:
    - { index: 16, color: '0xf99157' }
    - { index: 17, color: '0xd27b53' }
    - { index: 18, color: '0x393939' }
    - { index: 19, color: '0x515151' }
    - { index: 20, color: '0xa09f93' }
    - { index: 21, color: '0xe8e6df' }
