#!/bin/sh

current=$(git branchname)
destiny=${1:-master}

echo "fetching"
git fetch

echo "rebasing ${destiny}"
git checkout $destiny
# check if branch changed successfully (no staged changes or such things)
[[ $? == 0 ]] || exit "failed to switch to $destiny"
git rebase

echo "rebasing ${current} with ${destiny}"
git checkout $current
git pr-description $current | xclip -selection c || true
git rebase -i $destiny
git push -f

echo "merging"
git checkout $destiny
git merge --ff-only $current
git push
[[ $(git diff $current..$destiny) == "" ]] && git nuke $current $destiny

