#!/usr/bin/env bash

timetrap_now=`t n 2> /dev/null`
if [[ "$timetrap_now" =~ \@[a-zA-Z]* ]]; then
  project=${BASH_REMATCH[0]}
  echo "#[fg=green] $project asdasd #[default]"
else
  echo "#[fg=red] get to work #[default]"
  exit 1
fi
