[v1]
"cargo-bloat 0.11.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-upgrades 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-upgrades"]
"cargo-watch 8.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"diesel_cli 2.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["diesel"]
"reth 0.1.0-alpha.11 (path+file:///home/naps62/contrib/paradigmxyz/reth/bin/reth)" = ["reth"]
"sea-orm-cli 0.12.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "sea",
    "sea-orm-cli",
]
"tauri-cli 1.5.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tauri"]
"tokio-console 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokio-console"]
