#!/bin/sh

#
# Setup repository
#
git submodule init
git submodule update

#
# Setup rcup
#
ln -sf $PWD/rcrc $HOME/.rcrc

rcup

#
# Setup crontab
#
sudo cp setup.d/files/cron.naps62 /var/spool/cron/naps62

#
# Setup wallpaper rotator
#
(cd vendor/Daily-Reddit-Wallpaper; pip install --user --requirement requirements.txt)

