#!/usr/bin/env sh

alias reboot='sudo reboot'
alias halt='sudo poweroff'

alias apt='sudo aptitude'
alias open='xdg-open'

# alias git='hub'

# one-char aliases
alias a=ack
alias b=bundle
alias be='bundle exec'
alias c='cap'
alias cu='cucumber'
alias g=git
alias m=make
alias o=open
alias r=rails
alias rk=rake
alias s=ssh
alias t=tig
alias v=vim
alias va=vagrant
alias x=extract
alias y=yaourt

# cd
alias cd='cdls'
alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'

# ls
alias ls='ls --color'
alias ll='ls -alF'
alias la='ls -A'
alias lla='la -AlF'


# alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# proxy
alias proxy='source ${NAPS62_CONFDIR}/home/bin/proxy'
alias vim="stty stop '' -ixoff ; vim"
