#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-javascript,sql > /dev/null 2>&1
mv .git/tags.$$ .git/tags
