#!/bin/bash

eww="eww -c $HOME/.config/eww"
name="window_$1"
lock="$HOME/.cache/eww-${name}.lock"

if [[ ! -f "$lock" ]]; then
  ${eww} close calendar system music audio
  touch "$lock"
  ${eww} open ${name} && echo "ok good!"
else
  ${eww} close ${name}
  rm "$lock" && echo "closed"
fi
