#! /bin/bash

#initial check for occupied workspaces
for num in $(hyprctl workspaces | grep ID | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do 
  export o"$num"="$num"
done
 
#initial check for focused workspace
for num in $(hyprctl monitors | grep active | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do 
  export f"$num"="$num"
  export fnum=f"$num"
done

workspaces() {
if [[ ${1:0:9} == "workspace" ]]; then #set focused workspace
  unset -v "$fnum"
  num=${1:11}
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
  num=${1:17}
  export o"$num"="$num"
  export f"$num"="$num"

elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
  num=${1:18}
  unset -v o"$num" f"$num"
fi

function workspace_button() {
  ln=$1
  lo=$2
  lf=$3
  label=$4

  echo "(button :onclick 'hyprctl dispatch workspace $ln' :class 'w0$lo$lf' '${label}')"
}

#output eww widget

echo "
  (box \
    $(workspace_button 1 "$o1" "$f1" "1 󰊯") \
    $(workspace_button 2 "$o2" "$f2" "2 󰅩") \
    $(workspace_button 3 "$o3" "$f3" "3 󰭺") \
    $(workspace_button 4 "$o4" "$f4" "4 󰓇") \
    $(workspace_button 5 "$o5" "$f5" "5") \
    $(workspace_button 6 "$o6" "$f6" "6") \
  )"
}

workspaces

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
workspaces "$event"
done
