-- Standard awesome library
gears = require("gears")
awful = require("awful")
awful.rules = require("awful.rules")
require("awful.autofocus")
wibox     = require("wibox")
beautiful = require("beautiful")
naughty   = require("naughty")
drop      = require("scratchdrop")
lain      = require("lain")
vicious   = require("vicious")

require('10_error_handling')
require('20_globals')
require('25_autostart')
require('30_tags')
require('35_wallpaper')
require('40_menu')
require('45_widgets')
require('50_mouse_keyboard')
require('55_rules')
require('60_signals')

