#!/bin/bash

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# check window size after each command, and if necessary,
#   update values of LINES and COLUMNS
shopt -s checkwinsize

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# enable colors
COLORS_FILE=${NAPS62_CONFDIR}/files/bash/dircolors
test -r $COLORS_FILE && eval "$(dircolors -b $COLORS_FILE)" || eval "$(dircolors -b)"
