#!/bin/bash



function _git_prompt() {
  git branch &>/dev/null || return 1;

  local git_status="`git status -unormal 2>&1`"
  if ! [[ "$git_status" =~ Not\ a\ git\ repo ]]; then
    if [[ "$git_status" =~ nothing\ to\ commit ]]; then
      local ansi=32
    elif [[ "$git_status" =~ Changes\ not\ staged\ for\ commit ]]; then
      local ansi=33
    elif [[ "$git_status" =~ nothing\ added\ to\ commit\ but\ untracked\ files\ present ]]; then
      local ansi=33
    elif [[ "$(__git_ps1)" =~ MERGING ]]; then # if there are conflicts
      local ansi=31
    else
      local ansi=33
    fi

    echo -n "\[\033[01;"$ansi"m\]"
  fi
}

PS1_COLOR_NAME="\[\e[01;34m\]"
PS1_COLOR_DIR="\[\e[01;34m\]"
PS1_COLOR_PROMPTUSER="\[\e[01;32m\]"
PS1_COLOR_PROMPTROOT="\[\e[01;31m\]"
PS1_COLOR_CMD="\[\e[00m\]"
PS1_COLOR_GIT="\[\033[01;33m\]"
PS1_NAME="\u"
PS1_DIR="\W"
PS1_GIT="\$(__git_ps1)"
PS1_PROMPT_USER="\$ "
PS1_PROMPT_ROOT="# "
PS1_COLOR_GIT="`_git_prompt`"

#
# bash prompt
#
if [ `whoami` == "root" ]; then
  PS1_COLOR_PROMPT=$PS1_COLOR_PROMPTROOT
  PS1_PROMPT=$PS1_PROMPT_ROOT
else
  PS1_COLOR_PROMPT=$PS1_COLOR_PROMPTUSER
  PS1_PROMPT=$PS1_PROMPT_USER
fi

# show change signs in prompt
export GIT_SHOWDIRTYSTATE=1

function _prompt_command() {
  PS1='${debian_chroot:+($debian_chroot)}'
  PS1="${PS1} ${PS1_COLOR_DIR}${PS1_DIR}`_git_prompt`${PS1_GIT} ${PS1_COLOR_PROMPT}${PS1_PROMPT}${PS1_COLOR_CMD}"
}
PROMPT_COMMAND=_prompt_command
