gui:
  sidePanelWidth: 0.2 # number from 0 to 1
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red

git:
  paging:
    colorArg: always
    pager:
      delta --dark --paging=never --side-by-side
      #useConfig: false
  branchLogCmd: "git ls --"
