lastupdatecheck: 0
recentrepos:
- /home/naps62/projects/dotfiles
- /home/naps62/projects/cook
- /home/naps62/lightshift/ichi/vault_rebalance_strategies
startuppopupversion: 5
customcommandshistory:
- 'echo '
- echo 1
- quit
hidecommandlog: false
