#!/usr/bin/env sh

alias reboot='sudo reboot'
alias halt='sudo poweroff'

alias apt='sudo aptitude'
alias open='xdg-open'

eval "$(hub alias -s)"

# one-char aliases
alias a=ack
alias b=bundle
alias be='bundle exec'
alias cu='cucumber'
alias g=git
alias m=make
alias o=open
alias r=rails
alias rk=rake
alias s=ssh
alias v=vim
alias va=vagrant
alias x=extract
alias y=yaourt

alias c=crystal
alias cg=cargo

alias t=tmux
alias tn='tmux new -s'
alias ta='tmux attach -t'
alias tl='tmux list-sessions'
alias ts='tmux switch -t'
alias td='tmux detach'
alias tk='tmux kill-session -t'
alias tt='tmux choose-tree'

autoload -U zmv
alias mmv='noglob zmv -W'

# cd
alias cd='cdls'
alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'

# ls
alias ls='ls --color'
alias ll='ls -alF'
alias la='ls -A'
alias lla='la -AlF'


# alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# proxy
alias proxy='source ${NAPS62_CONFDIR}/home/bin/proxy'
alias vim="stty stop '' -ixoff ; vim"
