#!/usr/bin/env zsh

ZSH_THEME_GIT_PROMPT_PREFIX="${fg[blue]}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_NOCACHE=1

prompt_char () {
  echo -n "%{%B%} %(?.%F{green}.%F{red})"
  command git rev-parse --git-dir >/dev/null 2>/dev/null && echo '±' && return
  echo '%#'
}

case ${SOLARIZED_THEME:-dark} in
    light) bkg=white;;
    *)     bkg=black;;
esac

PROMPT='
 %{%B%F{blue}%}%~%{%B%F{green}%}%E%{%f%k%b%} $(git_prompt_info)
`prompt_char`%{%f%k%b%}%{$reset_color%} '
